defaultContentLanguage: "fr"
languageCode: fr
title: Ajiro
copyright: "&copy; 2016, Ajiro"
baseurl: http://ajiro.fr/
theme: template-ajiro

enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-89122379-1"
metaDataFormat: yaml
preserveTaxonomyNames: true

taxonomies:
  author: authors
  category: categories
  tag: tags

params:
  date_format:
    default: "Jan 2, 2006"
    iso: "2006-01-02T15:04:05-07:00"
  version:
    bootstrap: 4.0.0-alpha.5
    font_awesome: 4.7.0
    jquery: 3.1.1

menu:
  left:
    - Name: "Articles"
      Pre: "<i class='fa fa-file-text-o'></i>"
      URL: /articles/
      Weight: 10
    - Name: "Talks"
      Pre: "<i class='fa fa-desktop'></i>"
      URL: /talks/
      Weight: 20
    - Name: "Livres"
      Pre: "<i class='fa fa-book'></i>"
      URL: /books/
      Weight: 30
    - Name: "Ateliers"
      Pre: "<i class='fa fa-gamepad'></i>"
      URL: /games/
      Weight: 40
  right:
    - Name: "Auteurs"
      Pre: "<i class='fa fa-users'></i>"
      URL: /authors/
      Weight: 10
    - Name: "Tags"
      Pre: "<i class='fa fa-tags'></i>"
      URL: /tags/
      Weight: 20
    - Name: "Cat√©gories"
      Pre: "<i class='fa fa-folder-open'></i>"
      URL: /categories/
      Weight: 30
    - Name: "RSS"
      Pre: "<i class='fa fa-rss'></i>"
      URL: /index.xml
      Weight: 40

sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
